Fix missing attribute `_macro_paths` error
When I start with Galaxy

```
GALAXY_RUN_WITH_TEST_TOOLS=1 sh run.sh
```

I get this error

```
galaxy.tools.toolbox.base ERROR 2017-12-16 17:55:15,029 Error reading tool from path: cwl_tools/draft3/wc-tool.cwl
Traceback (most recent call last):
  File "/home/manabu/galaxy/lib/galaxy/tools/toolbox/base.py", line 587, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/home/manabu/galaxy/lib/galaxy/tools/toolbox/base.py", line 771, in load_tool
    tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 271, in create_tool
    return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 274, in _create_tool_from_source
    return create_tool_from_source(self.app, tool_source, **kwds)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 223, in create_tool_from_source
    tool = ToolClass(config_file, tool_source, app, **kwds)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 472, in __init__
    self.parse(tool_source, guid=guid, dynamic=dynamic)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 2422, in parse
    super(CwlTool, self).parse(tool_source, **kwds)
  File "/home/manabu/galaxy/lib/galaxy/tools/__init__.py", line 777, in parse
    self._macro_paths = tool_source._macro_paths
AttributeError: 'CwlToolSource' object has no attribute '_macro_paths'
```

At least this patch works on my environment.