Allow dev versions of CWL
Otherwise do_update (which we want to update from older CWL versions)
will update tools to the latest version, which may be a dev one,
causing errors like:

```
schema_salad.exceptions.ValidationException: Version 'v1.3.0-dev1' is a development or deprecated version.
 Update your document to a stable version (v1.0, v1.1, v1.2) or use --enable-dev to enable support for development and deprecated versions.
```

Together with the fixes to not unnecessarily recreate ToolProxy, fix
https://github.com/common-workflow-lab/galaxy/issues/147